### ISSUE TITLE
Sessions get invalidated when server restarts.

### ISSUE THREAD

**Issue by aarondyejr** [rynoV/tower-sessions-surrealdb-store#4]
Hello guys, 
I am running into an issue that I can't seem to track down, but it occurs whenever I restart the server (axum) it invalidates the session. I am not sure where this is coming from whether its tower-sessions-surrealdb-store or axum_login. Figured i'd open an issue here as well just in case, while I also ask in the repo for axum_login.

**Comment by rynoV** [comment]
What surrealdb backing store are you using? If it's getting deleted when the server restarts (like in-memory store) then this behaviour would be expected

If that doesn't help could you share code showing the issue?

**Comment by aarondyejr** [comment]
On the axum server I use the ws protocol to connect to surreal on my server, which uses rocksdb by the looks of it under the hood.

**Comment by rynoV** [comment]
Hard to say what the issue is without the code. I don't think there's anything in this package that would change between server restarts. If you swap out this session store with maybe the SQLite implementation that might rule out this package

**Comment by aarondyejr** [comment]
I just tested it out with the sqlx store and it also happens, so it seems to not be a store issue but rather a tower-session or axum_login issue. I appreciate your quick response, thank you for taking your time out of your day to respond :)
