### ISSUE TITLE
Improve Documentation / Beta Status

### ISSUE THREAD

**Issue by JuliDi** [rynoV/tower-sessions-surrealdb-store#7]
Hi,

I feel like this codebase is very solid already (especially has a ton of tests, that's great, thank you!), but it could profit from a bit more documentation. For example about the assumptions regarding how the database is set up.
When I started using it, I was wondering whether or not I would have to create a table or the crate would do it automatically. Turns out it does that automatically and it "just works".

Also, I would like it if the docs were similar to the "offical" session stores like this https://github.com/maxcountryman/tower-sessions-stores/tree/main/sqlx-store

Would you be accepting any PRs aligning this crate's docs (mostly the readme) with the other ones?

And what is missing to get this crate from its "beta" status to "production"?

**Comment by rynoV** [comment]
Thanks for your feedback

Would definitely accept PRs, agreed docs are lacking

As for the beta status, I just put that there out of caution. I'd like to see the crate used in a long-running server process under real load patterns before claiming it can handle it, even though I can't currently see a reason why it wouldn't work.

**Comment by JuliDi** [comment]
Great, I will send a PR in a few days :)

Regarding beta: we will hopefully be testing it more thoroughly, but from what I experienced so far, it looks very solid.
